Schedule leaderboard posts to a channel defined by environment variables
slack-samples/deno-virtual-running-buddies pull request #25
Opened 2023-09-28 22:48 UTC by zimeg

### Type of change

- [ ] New sample
- [x] New feature
- [x] Bug fix
- [ ] Documentation

### Summary

This PR uses environment variables to determine which channel the scheduled trigger will post to as a way to fix #14.

### Requirements

- [x] I’ve checked my submission against the Samples Checklist to ensure it complies with all standards
- [x] I have ensured the changes I am contributing align with existing patterns and have tested and linted my code
- [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct)

2023-09-28 22:49 UTC, zimeg commented on .env.example
> +RUNNERS_CHANNEL_ID=
This is left blank since a placeholder will allow the trigger to be successfully created even if that placeholder isn't a known channel!

2023-09-29 12:35 UTC, filmaj requested changes
Should we handle the error case? What if no `.env` file exists / the env var is empty when the user goes to create a trigger, or goes to deploy the app and auto-creates the trigger?

2023-10-16 22:00 UTC, zimeg commented
@filmaj I think an error would be expected in those cases and I'm not sure what a fallback might be since channel IDs aren't very predictable 🤔

The error from the hook calls out a `MissingEnvVarsError` error with the missing variable, which might be enough to correct this. Definitely open to suggestions on how else we might want to handle this!

2023-10-17 13:05 UTC, filmaj approved these changes

2023-10-18 17:29 UTC, merged